-- Ejecuta este archivo una sola vez en Supabase > SQL Editor.
-- Las tablas no aceptan escritura pública directa; el sitio accede desde sus
-- rutas privadas de servidor en Vercel.

create table if not exists public.relationship_state (
  story_key text primary key,
  accepted_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  title varchar(80) not null,
  caption varchar(300) not null default '',
  photo_url text not null,
  storage_path text not null unique,
  created_at timestamptz not null default now()
);

alter table public.relationship_state enable row level security;
alter table public.memories enable row level security;

-- Álbum público para que las fotos puedan mostrarse por URL.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'couple-photos',
  'couple-photos',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- No se crean políticas anónimas de escritura. La clave sb_secret_ (o la
-- service_role antigua) queda únicamente en Vercel y el formulario exige la
-- clave privada del álbum.
